#!/bin/bash
# COMPILE AND RUN C OR C++ FILES

# Name of output executable
EXECNAME=$(cut --delimiter=. --fields=1 <<<$1)

# remove executable if it exists
if [ -f "../build/$EXECNAME" ]; then
  echo "Removed previous executable"
	rm "../build/$EXECNAME"
fi

# Compile
g++ -ggdb -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion -Werror $1 -o "../build/$EXECNAME" &&
	# Make executable
	chmod +x "../build/$EXECNAME" &&
	# run
	../build/$EXECNAME
